POST http://10.10.10.107:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=123456&client_id=halo-admin&client_secret=123456

> {% client.global.set("token", "Bearer " + response.body.access_token) %}

### 管理员登录
GET http://127.0.0.1:9000/halo-admin/api/admin/user-info
Authorization: {{token}}
Accept: application/json

###
