insert into t_api values ("api:admin:isInstalled", null, "halo-admin", "api:admin:isInstalled", "Checks Installation status", "/api/admin/is_installed", "GET", 0, "Checks Installation status", 10101, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:login:precheck", null, "halo-admin", "api:admin:login:precheck", "Login", "/api/admin/login/precheck", "POST", 0, "Login", 10102, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:login", null, "halo-admin", "api:admin:login", "Login", "/api/admin/login", "POST", 0, "Login", 10103, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:logout", null, "halo-admin", "api:admin:logout", "Logs out (Clear session)", "/api/admin/logout", "POST", 0, "Logs out (Clear session)", 10104, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:password:code", null, "halo-admin", "api:admin:password:code", "Sends reset password verify code", "/api/admin/password/code", "POST", 0, "Sends reset password verify code", 10105, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:password:reset", null, "halo-admin", "api:admin:password:reset", "Resets password by verify code", "/api/admin/password/reset", "PUT", 0, "Resets password by verify code", 10106, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:refresh", null, "halo-admin", "api:admin:refresh", "Refreshes token", "/api/admin/refresh/{refreshToken}", "POST", 0, "Refreshes token", 10107, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:environments", null, "halo-admin", "api:admin:environments", "Gets environments info", "/api/admin/environments", "GET", 0, "Gets environments info", 10108, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:halo:logfile", null, "halo-admin", "api:admin:halo:logfile", "Gets halo log file content", "/api/admin/halo/logfile", "GET", 0, "Gets halo log file content", 10109, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:attachments:page", null, "halo-admin", "api:admin:attachments:page", "pageBy", "/api/admin/attachments", "GET", 0, "pageBy", 10201, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:attachments:loadById", null, "halo-admin", "api:admin:attachments:loadById", "Gets attachment detail by id", "/api/admin/attachments/{id}", "GET", 0, "Gets attachment detail by id", 10202, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:attachments:loadByAttachmentId", null, "halo-admin", "api:admin:attachments:loadByAttachmentId", "Updates a attachment", "/api/admin/attachments/{attachmentId}", "PUT", 0, "Updates a attachment", 10203, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:attachments:deleteById", null, "halo-admin", "api:admin:attachments:deleteById", "Deletes attachment permanently by id", "/api/admin/attachments/{id}", "DELETE", 0, "Deletes attachment permanently by id", 10204, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:attachments:batchDeleteById", null, "halo-admin", "api:admin:attachments:batchDeleteById", "Deletes attachments permanently in batch by id array", "/api/admin/attachments", "DELETE", 0, "Deletes attachments permanently in batch by id array", 10205, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:attachments:upload", null, "halo-admin", "api:admin:attachments:upload", "Uploads single file", "/api/admin/attachments/upload", "POST", 0, "Uploads single file", 10206, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:attachments:uploads", null, "halo-admin", "api:admin:attachments:uploads", "Uploads multi files (Invalid in Swagger UI)", "/api/admin/attachments/uploads", "POST", 0, "Uploads multi files (Invalid in Swagger UI)", 10207, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:attachments:mediaTypes", null, "halo-admin", "api:admin:attachments:mediaTypes", "Lists all of media types", "/api/admin/attachments/media_types", "GET", 0, "Lists all of media types", 10208, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:attachments:types", null, "halo-admin", "api:admin:attachments:types", "Lists all of types.", "/api/admin/attachments/types", "GET", 0, "Lists all of types.", 10209, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:backups:workDir:fetch", null, "halo-admin", "api:admin:backups:workDir:fetch", "getWorkDirBackup", "/api/admin/backups/work-dir/fetch", "GET", 0, "getWorkDirBackup", 10301, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:data:fetch", null, "halo-admin", "api:admin:backups:data:fetch", "getDataBackup", "/api/admin/backups/data/fetch", "GET", 0, "getDataBackup", 10302, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:markdown:fetch", null, "halo-admin", "api:admin:backups:markdown:fetch", "getMarkdownBackup", "/api/admin/backups/markdown/fetch", "GET", 0, "getMarkdownBackup", 10303, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:workDir", null, "halo-admin", "api:admin:backups:workDir", "Backups work directory", "/api/admin/backups/work-dir", "POST", 0, "Backups work directory", 10304, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:workDir:options", null, "halo-admin", "api:admin:backups:workDir:options", "Gets items that can be backed up", "/api/admin/backups/work-dir/options", "GET", 0, "Gets items that can be backed up", 10305, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:workDir:all", null, "halo-admin", "api:admin:backups:workDir:all", "Gets all work directory backups", "/api/admin/backups/work-dir", "GET", 0, "Gets all work directory backups", 10306, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:workDir:download", null, "halo-admin", "api:admin:backups:workDir:download", "Downloads a work directory backup file", "/api/admin/backups/work-dir/{filename}", "GET", 0, "Downloads a work directory backup file", 10307, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:workDir:delete", null, "halo-admin", "api:admin:backups:workDir:delete", "Deletes a work directory backup", "/api/admin/backups/work-dir", "DELETE", 0, "Deletes a work directory backup", 10308, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:markdown:import", null, "halo-admin", "api:admin:backups:markdown:import", "Imports markdown", "/api/admin/backups/markdown/import", "POST", 0, "Imports markdown", 10309, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:data:export", null, "halo-admin", "api:admin:backups:data:export", "Exports all data", "/api/admin/backups/data", "POST", 0, "Exports all data", 10310, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:data:all", null, "halo-admin", "api:admin:backups:data:all", "Lists all exported data", "/api/admin/backups/data", "GET", 0, "Lists all exported data", 10311, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:data:delete", null, "halo-admin", "api:admin:backups:data:delete", "Deletes a exported data", "/api/admin/backups/data", "DELETE", 0, "Deletes a exported data", 10312, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:data:download", null, "halo-admin", "api:admin:backups:data:download", "Downloads a exported data", "/api/admin/backups/data/{fileName}", "GET", 0, "Downloads a exported data", 10313, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:markdown:export", null, "halo-admin", "api:admin:backups:markdown:export", "Exports markdowns", "/api/admin/backups/markdown/export", "POST", 0, "Exports markdowns", 10314, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:markdown:export:all", null, "halo-admin", "api:admin:backups:markdown:export:all", "Gets all markdown backups", "/api/admin/backups/markdown/export", "GET", 0, "Gets all markdown backups", 10315, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:markdown:export:delete", null, "halo-admin", "api:admin:backups:markdown:export:delete", "Deletes a markdown backup", "/api/admin/backups/markdown/export", "DELETE", 0, "Deletes a markdown backup", 10316, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:backups:markdown:export:download", null, "halo-admin", "api:admin:backups:markdown:export:download", "Downloads a work markdown backup file", "/api/admin/backups/markdown/export/{fileName}", "GET", 0, "Downloads a work markdown backup file", 10317, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:categories:loadById", null, "halo-admin", "api:admin:categories:loadById", "Gets category detail", "/api/admin/categories/{categoryId}", "GET", 0, "Gets category detail", 10401, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:categories:all", null, "halo-admin", "api:admin:categories:all", "Lists all categories", "/api/admin/categories", "GET", 0, "Lists all categories", 10402, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:categories:treeView", null, "halo-admin", "api:admin:categories:treeView", "List all categories as tree", "/api/admin/categories/tree_view", "GET", 0, "List all categories as tree", 10403, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:categories:create", null, "halo-admin", "api:admin:categories:create", "Creates category", "/api/admin/categories", "POST", 0, "Creates category", 10404, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:categories:updateById", null, "halo-admin", "api:admin:categories:updateById", "Updates category", "/api/admin/categories/{categoryId}", "PUT", 0, "Updates category", 10405, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:categories:batch", null, "halo-admin", "api:admin:categories:batch", "Updates category in batch", "/api/admin/categories/batch", "PUT", 0, "Updates category in batch", 10406, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:categories:deleteById", null, "halo-admin", "api:admin:categories:deleteById", "Deletes category", "/api/admin/categories/{categoryId}", "DELETE", 0, "Deletes category", 10407, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:installations:create", null, "halo-admin", "api:admin:installations:create", "Initializes the blog", "/api/admin/installations", "POST", 0, "Initializes the blog", 10501, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:journals:comments:search", null, "halo-admin", "api:admin:journals:comments:search", "Lists journal comments", "/api/admin/journals/comments", "GET", 0, "Lists journal comments", 10601, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:comments:latest", null, "halo-admin", "api:admin:journals:comments:latest", "Lists latest journal comments", "/api/admin/journals/comments/latest", "GET", 0, "Lists latest journal comments", 10602, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:comments:tree", null, "halo-admin", "api:admin:journals:comments:tree", "Lists comments with tree view", "/api/admin/journals/comments/{journalId}/tree_view", "GET", 0, "Lists comments with tree view", 10603, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:comments:list", null, "halo-admin", "api:admin:journals:comments:list", "Lists comment with list view", "/api/admin/journals/comments/{journalId}/list_view", "GET", 0, "Lists comment with list view", 10604, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:comments:create", null, "halo-admin", "api:admin:journals:comments:create", "Creates a journal comment", "/api/admin/journals/comments", "POST", 0, "Creates a journal comment", 10605, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:comments:status", null, "halo-admin", "api:admin:journals:comments:status", "Updates comment status", "/api/admin/journals/comments/{commentId}/status/{status}", "PUT", 0, "Updates comment status", 10606, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:comments:updateById", null, "halo-admin", "api:admin:journals:comments:updateById", "Updates a journal comment by comment id", "/api/admin/journals/comments/{commentId}", "PUT", 0, "Updates a journal comment by comment id", 10607, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:comments:deleteById", null, "halo-admin", "api:admin:journals:comments:deleteById", "Deletes comment permanently and recursively", "/api/admin/journals/comments/{commentId}", "DELETE", 0, "Deletes comment permanently and recursively", 10608, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:journals:search", null, "halo-admin", "api:admin:journals:search", "Lists journals", "/api/admin/journals", "GET", 0, "Lists journals", 10701, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:latest", null, "halo-admin", "api:admin:journals:latest", "Gets latest journals", "/api/admin/journals/latest", "GET", 0, "Gets latest journals", 10702, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:create", null, "halo-admin", "api:admin:journals:create", "Creates a journal", "/api/admin/journals", "POST", 0, "Creates a journal", 10703, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:updateById", null, "halo-admin", "api:admin:journals:updateById", "Updates a Journal", "/api/admin/journals/{id}", "PUT", 0, "Updates a Journal", 10704, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:journals:deleteById", null, "halo-admin", "api:admin:journals:deleteById", "Delete journal", "/api/admin/journals/{journalId}", "DELETE", 0, "Delete journal", 10705, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:links:search", null, "halo-admin", "api:admin:links:search", "Lists links", "/api/admin/links", "GET", 0, "Lists links", 10801, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:links:loadById", null, "halo-admin", "api:admin:links:loadById", "Gets link detail by id", "/api/admin/links/{id}", "GET", 0, "Gets link detail by id", 10802, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:links:create", null, "halo-admin", "api:admin:links:create", "Creates a link", "/api/admin/links", "POST", 0, "Creates a link", 10803, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:links:updateById", null, "halo-admin", "api:admin:links:updateById", "Updates a link", "/api/admin/links/{id}", "PUT", 0, "Updates a link", 10804, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:links:deleteById", null, "halo-admin", "api:admin:links:deleteById", "Delete link by id", "/api/admin/links/{id}", "DELETE", 0, "Delete link by id", 10805, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:links:teams", null, "halo-admin", "api:admin:links:teams", "Lists all link teams", "/api/admin/links/teams", "GET", 0, "Lists all link teams", 10806, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:logs:latest", null, "halo-admin", "api:admin:logs:latest", "Pages latest logs", "/api/admin/logs/latest", "GET", 0, "Pages latest logs", 10901, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:logs:search", null, "halo-admin", "api:admin:logs:search", "Lists logs", "/api/admin/logs", "GET", 0, "Lists logs", 10902, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:logs:clear", null, "halo-admin", "api:admin:logs:clear", "Clears all logs", "/api/admin/logs/clear", "GET", 0, "Clears all logs", 10903, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:mails:test", null, "halo-admin", "api:admin:mails:test", "Tests the SMTP service", "/api/admin/mails/test", "POST", 0, "Tests the SMTP service", 11001, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:mails:test:connection", null, "halo-admin", "api:admin:mails:test:connection", "Test connection with email server", "/api/admin/mails/test/connection", "POST", 0, "Test connection with email server", 11002, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:menus:search", null, "halo-admin", "api:admin:menus:search", "Lists all menus", "/api/admin/menus", "GET", 0, "Lists all menus", 11101, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:treeView", null, "halo-admin", "api:admin:menus:treeView", "Lists menus as tree", "/api/admin/menus/tree_view", "GET", 0, "Lists menus as tree", 11102, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:team:treeView", null, "halo-admin", "api:admin:menus:team:treeView", "Lists menus as tree by team", "/api/admin/menus/team/tree_view", "GET", 0, "Lists menus as tree by team", 11103, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:loadById", null, "halo-admin", "api:admin:menus:loadById", "Gets menu detail by id", "/api/admin/menus/{menuId}", "GET", 0, "Gets menu detail by id", 11104, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:create", null, "halo-admin", "api:admin:menus:create", "Creates a menu", "/api/admin/menus", "POST", 0, "Creates a menu", 11105, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:batchCreate", null, "halo-admin", "api:admin:menus:batchCreate", "createBatchBy", "/api/admin/menus/batch", "POST", 0, "createBatchBy", 11106, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:updateById", null, "halo-admin", "api:admin:menus:updateById", "Updates a menu", "/api/admin/menus/{menuId}", "PUT", 0, "Updates a menu", 11107, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:batchUpdate", null, "halo-admin", "api:admin:menus:batchUpdate", "updateBatchBy", "/api/admin/menus/batch", "PUT", 0, "updateBatchBy", 11108, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:deleteById", null, "halo-admin", "api:admin:menus:deleteById", "Deletes a menu", "/api/admin/menus/{menuId}", "DELETE", 0, "Deletes a menu", 11109, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:batchDelete", null, "halo-admin", "api:admin:menus:batchDelete", "deleteBatchBy", "/api/admin/menus/batch", "DELETE", 0, "deleteBatchBy", 11110, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:menus:teams", null, "halo-admin", "api:admin:menus:teams", "Lists all menu teams", "/api/admin/menus/teams", "GET", 0, "Lists all menu teams", 11111, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:migrations:halo", null, "halo-admin", "api:admin:migrations:halo", "Migrate from Halo", "/api/admin/migrations/halo", "POST", 0, "Migrate from Halo", 11201, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:options:search", null, "halo-admin", "api:admin:options:search", "Lists options", "/api/admin/options", "GET", 0, "Lists options", 11301, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:saving", null, "halo-admin", "api:admin:options:saving", "Saves options", "/api/admin/options/saving", "POST", 0, "Saves options", 11302, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:mapView", null, "halo-admin", "api:admin:options:mapView", "Lists all options with map view", "/api/admin/options/map_view", "GET", 0, "Lists all options with map view", 11303, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:mapView:keys", null, "halo-admin", "api:admin:options:mapView:keys", "Lists options with map view by keys", "/api/admin/options/map_view/keys", "POST", 0, "Lists options with map view by keys", 11304, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:listView", null, "halo-admin", "api:admin:options:listView", "Lists all options with list view", "/api/admin/options/list_view", "GET", 0, "Lists all options with list view", 11305, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:loadById", null, "halo-admin", "api:admin:options:loadById", "Gets option detail by id", "/api/admin/options/{id}", "GET", 0, "Gets option detail by id", 11306, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:create", null, "halo-admin", "api:admin:options:create", "Creates option", "/api/admin/options", "POST", 0, "Creates option", 11307, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:updateById", null, "halo-admin", "api:admin:options:updateById", "Updates option", "/api/admin/options/{optionId}", "PUT", 0, "Updates option", 11308, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:deleteById", null, "halo-admin", "api:admin:options:deleteById", "Deletes option", "/api/admin/options/{optionId}", "DELETE", 0, "Deletes option", 11309, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:options:mapView:saving", null, "halo-admin", "api:admin:options:mapView:saving", "Saves options by option map", "/api/admin/options/map_view/saving", "POST", 0, "Saves options by option map", 11310, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:photos:latest", null, "halo-admin", "api:admin:photos:latest", "Lists latest photos", "/api/admin/photos/latest", "GET", 0, "Lists latest photos", 11401, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:search", null, "halo-admin", "api:admin:photos:search", "Lists photos", "/api/admin/photos", "GET", 0, "Lists photos", 11402, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:loadById", null, "halo-admin", "api:admin:photos:loadById", "Gets photo detail by id", "/api/admin/photos/{photoId}", "GET", 0, "Gets photo detail by id", 11403, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:deleteById", null, "halo-admin", "api:admin:photos:deleteById", "Deletes photo by id", "/api/admin/photos/{photoId}", "DELETE", 0, "Deletes photo by id", 11404, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:batchDelete", null, "halo-admin", "api:admin:photos:batchDelete", "Deletes photos permanently in batch by id array", "/api/admin/photos/batch", "DELETE", 0, "Deletes photos permanently in batch by id array", 11405, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:create", null, "halo-admin", "api:admin:photos:create", "Creates a photo", "/api/admin/photos", "POST", 0, "Creates a photo", 11406, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:batchCreate", null, "halo-admin", "api:admin:photos:batchCreate", "Batch creation photos", "/api/admin/photos/batch", "POST", 0, "Batch creation photos", 11407, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:updateById", null, "halo-admin", "api:admin:photos:updateById", "Updates a photo", "/api/admin/photos/{photoId}", "PUT", 0, "Updates a photo", 11408, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:batchUpdate", null, "halo-admin", "api:admin:photos:batchUpdate", "Updates photo in batch", "/api/admin/photos/batch", "PUT", 0, "Updates photo in batch", 11409, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:likes", null, "halo-admin", "api:admin:photos:likes", "Likes a photo", "/api/admin/photos/{photoId}/likes", "PUT", 0, "Likes a photo", 11410, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:photos:teams", null, "halo-admin", "api:admin:photos:teams", "Lists all of photo teams", "/api/admin/photos/teams", "GET", 0, "Lists all of photo teams", 11411, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:posts:comments:search", null, "halo-admin", "api:admin:posts:comments:search", "Lists post comments", "/api/admin/posts/comments", "GET", 0, "Lists post comments", 11501, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:latest", null, "halo-admin", "api:admin:posts:comments:latest", "Pages post latest comments", "/api/admin/posts/comments/latest", "GET", 0, "Pages post latest comments", 11502, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:posts:tree", null, "halo-admin", "api:admin:posts:comments:posts:tree", "Lists post comments with tree view", "/api/admin/posts/comments/{postId}/tree_view", "GET", 0, "Lists post comments with tree view", 11503, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:posts:search", null, "halo-admin", "api:admin:posts:comments:posts:search", "Lists post comment with list view", "/api/admin/posts/comments/{postId}/list_view", "GET", 0, "Lists post comment with list view", 11504, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:create", null, "halo-admin", "api:admin:posts:comments:create", "Creates a post comment (new or reply)", "/api/admin/posts/comments", "POST", 0, "Creates a post comment (new or reply)", 11505, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:status", null, "halo-admin", "api:admin:posts:comments:status", "Updates post comment status", "/api/admin/posts/comments/{commentId}/status/{status}", "PUT", 0, "Updates post comment status", 11506, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:status:update", null, "halo-admin", "api:admin:posts:comments:status:update", "Updates post comment status in batch", "/api/admin/posts/comments/status/{status}", "PUT", 0, "Updates post comment status in batch", 11507, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:deleteById", null, "halo-admin", "api:admin:posts:comments:deleteById", "Deletes post comment permanently and recursively", "/api/admin/posts/comments/{commentId}", "DELETE", 0, "Deletes post comment permanently and recursively", 11508, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:batchDeleteByIds", null, "halo-admin", "api:admin:posts:comments:batchDeleteByIds", "Delete post comments permanently in batch by id array", "/api/admin/posts/comments", "DELETE", 0, "Delete post comments permanently in batch by id array", 11509, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:loadById", null, "halo-admin", "api:admin:posts:comments:loadById", "Gets a post comment by comment id", "/api/admin/posts/comments/{commentId}", "GET", 0, "Gets a post comment by comment id", 11510, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:comments:updateById", null, "halo-admin", "api:admin:posts:comments:updateById", "Updates a post comment", "/api/admin/posts/comments/{commentId}", "PUT", 0, "Updates a post comment", 11511, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:posts:search", null, "halo-admin", "api:admin:posts:search", "Lists posts", "/api/admin/posts", "GET", 0, "Lists posts", 11601, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:latest", null, "halo-admin", "api:admin:posts:latest", "Pages latest post", "/api/admin/posts/latest", "GET", 0, "Pages latest post", 11602, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:status", null, "halo-admin", "api:admin:posts:status", "Gets a page of post by post status", "/api/admin/posts/status/{status}", "GET", 0, "Gets a page of post by post status", 11603, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:loadById", null, "halo-admin", "api:admin:posts:loadById", "Gets a post", "/api/admin/posts/{postId}", "GET", 0, "Gets a post", 11604, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:likes", null, "halo-admin", "api:admin:posts:likes", "Likes a post", "/api/admin/posts/{postId}/likes", "PUT", 0, "Likes a post", 11605, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:create", null, "halo-admin", "api:admin:posts:create", "Creates a post", "/api/admin/posts", "POST", 0, "Creates a post", 11606, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:updateById", null, "halo-admin", "api:admin:posts:updateById", "Updates a post", "/api/admin/posts/{postId}", "PUT", 0, "Updates a post", 11607, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:status:update", null, "halo-admin", "api:admin:posts:status", "Updates post status", "/api/admin/posts/{postId}/status/{status}", "PUT", 0, "Updates post status", 11608, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:status:batchUpdate", null, "halo-admin", "api:admin:posts:status:update", "Updates post status in batch", "/api/admin/posts/status/{status}", "PUT", 0, "Updates post status in batch", 11609, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:status:draft", null, "halo-admin", "api:admin:posts:status:draft", "Updates draft", "/api/admin/posts/{postId}/status/draft/content", "PUT", 0, "Updates draft", 11610, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:deleteById", null, "halo-admin", "api:admin:posts:deleteById", "Deletes a photo permanently", "/api/admin/posts/{postId}", "DELETE", 0, "Deletes a photo permanently", 11611, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:batchDeleteByIds", null, "halo-admin", "api:admin:posts:batchDeleteByIds", "Deletes posts permanently in batch by id array", "/api/admin/posts", "DELETE", 0, "Deletes posts permanently in batch by id array", 11612, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:posts:preview", null, "halo-admin", "api:admin:posts:preview", "Gets a post preview link", "/api/admin/posts/preview/{postId}", "GET", 0, "Gets a post preview link", 11613, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:sheets:comments:search", null, "halo-admin", "api:admin:sheets:comments:search", "Lists sheet comments", "/api/admin/sheets/comments", "GET", 0, "Lists sheet comments", 11701, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:latest", null, "halo-admin", "api:admin:sheets:comments:latest", "Lists latest sheet comments", "/api/admin/sheets/comments/latest", "GET", 0, "Lists latest sheet comments", 11702, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:tree", null, "halo-admin", "api:admin:sheets:comments:tree", "Lists sheet comments with tree view", "/api/admin/sheets/comments/{sheetId}/tree_view", "GET", 0, "Lists sheet comments with tree view", 11703, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:list", null, "halo-admin", "api:admin:sheets:comments:list", "Lists sheet comment with list view", "/api/admin/sheets/comments/{sheetId}/list_view", "GET", 0, "Lists sheet comment with list view", 11704, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:create", null, "halo-admin", "api:admin:sheets:comments:create", "Creates a sheet comment (new or reply)", "/api/admin/sheets/comments", "POST", 0, "Creates a sheet comment (new or reply)", 11705, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:status", null, "halo-admin", "api:admin:sheets:comments:status", "Updates sheet comment status", "/api/admin/sheets/comments/{commentId}/status/{status}", "PUT", 0, "Updates sheet comment status", 11706, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:status:update", null, "halo-admin", "api:admin:sheets:comments:status:update", "Updates sheet comment status in batch", "/api/admin/sheets/comments/status/{status}", "PUT", 0, "Updates sheet comment status in batch", 11707, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:deleteById", null, "halo-admin", "api:admin:sheets:comments:deleteById", "Deletes sheet comment permanently and recursively", "/api/admin/sheets/comments/{commentId}", "DELETE", 0, "Deletes sheet comment permanently and recursively", 11708, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:batchDeleteByIds", null, "halo-admin", "api:admin:sheets:comments:batchDeleteByIds", "Deletes sheet comments permanently in batch by id array", "/api/admin/sheets/comments", "DELETE", 0, "Deletes sheet comments permanently in batch by id array", 11709, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:loadById", null, "halo-admin", "api:admin:sheets:comments:loadById", "Gets a sheet comment by comment id", "/api/admin/sheets/comments/{commentId}", "GET", 0, "Gets a sheet comment by comment id", 11710, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:comments:updateById", null, "halo-admin", "api:admin:sheets:comments:updateById", "Updates a sheet comment", "/api/admin/sheets/comments/{commentId}", "PUT", 0, "Updates a sheet comment", 11711, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:sheets:loadById", null, "halo-admin", "api:admin:sheets:loadById", "Gets a sheet", "/api/admin/sheets/{sheetId}", "GET", 0, "Gets a sheet", 11801, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:page", null, "halo-admin", "api:admin:sheets:page", "Gets a page of sheet", "/api/admin/sheets", "GET", 0, "Gets a page of sheet", 11802, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:independent", null, "halo-admin", "api:admin:sheets:independent", "Lists independent sheets", "/api/admin/sheets/independent", "GET", 0, "Lists independent sheets", 11803, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:create", null, "halo-admin", "api:admin:sheets:create", "Creates a sheet", "/api/admin/sheets", "POST", 0, "Creates a sheet", 11804, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:updateById", null, "halo-admin", "api:admin:sheets:updateById", "Updates a sheet", "/api/admin/sheets/{sheetId}", "PUT", 0, "Updates a sheet", 11805, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:updateStatus", null, "halo-admin", "api:admin:sheets:updateStatus", "Updates a sheet", "/api/admin/sheets/{sheetId}/{status}", "PUT", 0, "Updates a sheet", 11806, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:status:draft", null, "halo-admin", "api:admin:sheets:status:draft", "Updates draft", "/api/admin/sheets/{sheetId}/status/draft/content", "PUT", 0, "Updates draft", 11807, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:deleteById", null, "halo-admin", "api:admin:sheets:deleteById", "Deletes a sheet", "/api/admin/sheets/{sheetId}", "DELETE", 0, "Deletes a sheet", 11808, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:sheets:preview", null, "halo-admin", "api:admin:sheets:preview", "Gets a sheet preview link", "/api/admin/sheets/preview/{sheetId}", "GET", 0, "Gets a sheet preview link", 11809, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:statics:search", null, "halo-admin", "api:admin:statics:search", "Lists static files", "/api/admin/statics", "GET", 0, "Lists static files", 11901, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:statics:delete", null, "halo-admin", "api:admin:statics:delete", "Deletes file by relative path", "/api/admin/statics", "DELETE", 0, "Deletes file by relative path", 11902, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:statics:create", null, "halo-admin", "api:admin:statics:create", "Creates a folder", "/api/admin/statics", "POST", 0, "Creates a folder", 11903, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:statics:upload", null, "halo-admin", "api:admin:statics:upload", "Uploads static file", "/api/admin/statics/upload", "POST", 0, "Uploads static file", 11904, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:statics:rename", null, "halo-admin", "api:admin:statics:rename", "Renames static file", "/api/admin/statics/rename", "POST", 0, "Renames static file", 11905, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:statics:files", null, "halo-admin", "api:admin:statics:files", "Save static file", "/api/admin/statics/files", "PUT", 0, "Save static file", 11906, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:statistics:get", null, "halo-admin", "api:admin:statistics:get", "Gets blog statistics.", "/api/admin/statistics", "GET", 0, "Gets blog statistics.", 12001, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:statistics:user", null, "halo-admin", "api:admin:statistics:user", "Gets blog statistics with user", "/api/admin/statistics/user", "GET", 0, "Gets blog statistics with user", 12002, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:tags:search", null, "halo-admin", "api:admin:tags:search", "Lists tags", "/api/admin/tags", "GET", 0, "Lists tags", 12101, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:tags:create", null, "halo-admin", "api:admin:tags:create", "Creates a tag", "/api/admin/tags", "POST", 0, "Creates a tag", 12102, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:tags:loadById", null, "halo-admin", "api:admin:tags:loadById", "Gets tag detail by id", "/api/admin/tags/{tagId}", "GET", 0, "Gets tag detail by id", 12103, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:tags:updateById", null, "halo-admin", "api:admin:tags:updateById", "Updates a tag", "/api/admin/tags/{tagId}", "PUT", 0, "Updates a tag", 12104, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:tags:deleteById", null, "halo-admin", "api:admin:tags:deleteById", "Deletes a tag", "/api/admin/tags/{tagId}", "DELETE", 0, "Deletes a tag", 12105, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:themes:loadById", null, "halo-admin", "api:admin:themes:loadById", "Gets theme property by theme id", "/api/admin/themes/{themeId}", "GET", 0, "Gets theme property by theme id", 12201, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:all", null, "halo-admin", "api:admin:themes:all", "Lists all themes", "/api/admin/themes", "GET", 0, "Lists all themes", 12202, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:activation:files", null, "halo-admin", "api:admin:themes:activation:files", "Lists all activate theme files", "/api/admin/themes/activation/files", "GET", 0, "Lists all activate theme files", 12203, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:files", null, "halo-admin", "api:admin:themes:files", "Lists theme files by theme id", "/api/admin/themes/{themeId}/files", "GET", 0, "Lists theme files by theme id", 12204, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:files:content", null, "halo-admin", "api:admin:themes:files:content", "Gets template content", "/api/admin/themes/files/content", "GET", 0, "Gets template content", 12205, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:files:content:load", null, "halo-admin", "api:admin:themes:files:content:load", "Gets template content by theme id", "/api/admin/themes/{themeId}/files/content", "GET", 0, "Gets template content by theme id", 12206, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:files:content:update", null, "halo-admin", "api:admin:themes:files:content", "Updates template content", "/api/admin/themes/files/content", "PUT", 0, "Updates template content", 12207, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:files:content:updateById", null, "halo-admin", "api:admin:themes:files:content:updateById", "Updates template content by theme id", "/api/admin/themes/{themeId}/files/content", "PUT", 0, "Updates template content by theme id", 12208, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:activation:template:custom:sheet", null, "halo-admin", "api:admin:themes:activation:template:custom:sheet", "Gets custom sheet templates", "/api/admin/themes/activation/template/custom/sheet", "GET", 0, "Gets custom sheet templates", 12209, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:activation:template:custom:post", null, "halo-admin", "api:admin:themes:activation:template:custom:post", "Gets custom post templates", "/api/admin/themes/activation/template/custom/post", "GET", 0, "Gets custom post templates", 12210, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:active", null, "halo-admin", "api:admin:themes:active", "Activates a theme", "/api/admin/themes/{themeId}/activation", "POST", 0, "Activates a theme", 12211, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:activation", null, "halo-admin", "api:admin:themes:activation", "Gets activate theme", "/api/admin/themes/activation", "GET", 0, "Gets activate theme", 12212, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:activation:configurations", null, "halo-admin", "api:admin:themes:activation:configurations", "Fetches activated theme configuration", "/api/admin/themes/activation/configurations", "GET", 0, "Fetches activated theme configuration", 12213, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:configurations", null, "halo-admin", "api:admin:themes:configurations", "Fetches theme configuration by theme id", "/api/admin/themes/{themeId}/configurations", "GET", 0, "Fetches theme configuration by theme id", 12214, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:configurations:groups", null, "halo-admin", "api:admin:themes:configurations:groups", "Fetches theme configuration by theme id and group name", "/api/admin/themes/{themeId}/configurations/groups/{group}", "GET", 0, "Fetches theme configuration by theme id and group name", 12215, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:configurations:fetchById", null, "halo-admin", "api:admin:themes:configurations:fetchById", "Fetches theme configuration group names by theme id", "/api/admin/themes/{themeId}/configurations/groups", "GET", 0, "Fetches theme configuration group names by theme id", 12216, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:activation:settings", null, "halo-admin", "api:admin:themes:activation:settings", "Lists activated theme settings", "/api/admin/themes/activation/settings", "GET", 0, "Lists activated theme settings", 12217, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:settings", null, "halo-admin", "api:admin:themes:settings", "Lists theme settings by theme id", "/api/admin/themes/{themeId}/settings", "GET", 0, "Lists theme settings by theme id", 12218, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:settiongs:groups", null, "halo-admin", "api:admin:themes:settiongs:groups", "Lists theme settings by theme id and group name", "/api/admin/themes/{themeId}/groups/{group}/settings", "GET", 0, "Lists theme settings by theme id and group name", 12219, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:activation:settings:save", null, "halo-admin", "api:admin:themes:activation:settings", "Saves theme settings", "/api/admin/themes/activation/settings", "POST", 0, "Saves theme settings", 12220, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:settings:save", null, "halo-admin", "api:admin:themes:settings:save", "Saves theme settings", "/api/admin/themes/{themeId}/settings", "POST", 0, "Saves theme settings", 12221, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:deleteById", null, "halo-admin", "api:admin:themes:deleteById", "Deletes a theme", "/api/admin/themes/{themeId}", "DELETE", 0, "Deletes a theme", 12222, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:upload", null, "halo-admin", "api:admin:themes:upload", "Uploads a theme", "/api/admin/themes/upload", "POST", 0, "Uploads a theme", 12223, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:uploadById", null, "halo-admin", "api:admin:themes:uploadById", "Upgrades theme by file", "/api/admin/themes/upload/{themeId}", "PUT", 0, "Upgrades theme by file", 12224, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:fetching", null, "halo-admin", "api:admin:themes:fetching", "Fetches a new theme", "/api/admin/themes/fetching", "POST", 0, "Fetches a new theme", 12225, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:fetchingById", null, "halo-admin", "api:admin:themes:fetchingById", "Upgrades theme from remote", "/api/admin/themes/fetching/{themeId}", "PUT", 0, "Upgrades theme from remote", 12226, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:reload", null, "halo-admin", "api:admin:themes:reload", "Reloads themes", "/api/admin/themes/reload", "POST", 0, "Reloads themes", 12227, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:themes:activation:template:exists", null, "halo-admin", "api:admin:themes:activation:template:exists", "Determines if template exists", "/api/admin/themes/activation/template/exists", "GET", 0, "Determines if template exists", 12228, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:users:profiles", null, "halo-admin", "api:admin:users:profiles", "Gets user profile", "/api/admin/users/profiles", "GET", 0, "Gets user profile", 12301, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:users:profiles:update", null, "halo-admin", "api:admin:users:profiles", "Updates user profile", "/api/admin/users/profiles", "PUT", 0, "Updates user profile", 12302, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:users:profiles:password", null, "halo-admin", "api:admin:users:profiles:password", "Updates user's password", "/api/admin/users/profiles/password", "PUT", 0, "Updates user's password", 12303, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:users:mfa:generate", null, "halo-admin", "api:admin:users:mfa:generate", "Generate Multi-Factor Auth qr image", "/api/admin/users/mfa/generate", "PUT", 0, "Generate Multi-Factor Auth qr image", 12304, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);
insert into t_api values ("api:admin:users:mfa:update", null, "halo-admin", "api:admin:users:mfa:update", "Updates user's Multi Factor Auth", "/api/admin/users/mfa/update", "PUT", 0, "Updates user's Multi Factor Auth", 12305, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

insert into t_api values ("api:admin:userInfo", null, "halo-admin", "api:admin:userInfo", "userInfo", "/api/admin/user-info", "GET", 0, "userInfo", 12401, 1, 0, now(), "@SYSTEM", null, null, null, null, null, null, null);

